//
//  ContentView.swift
//  Motivation Management
//
//  Created by PhantomKing on 1/12/2022.
//

import SwiftUI
import DesignSystem

struct ContentView: View {
    var body: some View {
        VStack(spacing: 42.60) {
            ZStack {
                    Text("Log in")
                    .fontWeight(.medium)
                    .font(.title3)
                    .lineSpacing(28)
                    .offset(x: 1, y: 22)

                    RoundedRectangle(cornerRadius: 8)
                    .fill(Color(red: 0.50, green: 0.23, blue: 0.27, opacity: 0.50))
                    .offset(x: -155.50, y: 20)
                    .frame(width: 24, height: 24)

                    HStack(spacing: 132.62) {
                    ZStack {
                    }

                                RoundedRectangle(cornerRadius: 8)
                                .fill(Color(red: 0.11, green: 0.14, blue: 0.18))
                                .frame(width: 28.43, height: 11.09)

                                ZStack {
                                            RoundedRectangle(cornerRadius: 8)
                                            .fill(Color(red: 0.50, green: 0.23, blue: 0.27, opacity: 0.50))
                                            .frame(width: 24.33, height: 11.33)
                                }
                                .frame(width: 66.66, height: 11.34)
                    }
                    .padding(.trailing, 15)
                    .padding(.bottom, 15)
                    .offset(x: 0, y: -22)
                    .frame(width: 375, height: 44)
            }
            .frame(width: 375, height: 88)
            .background(Color(red: 1, green: 1, blue: 1, opacity: 0))

            VStack() {
                    HStack(spacing: 115) {
                        Text("Username or Email")
                        .font(.callout)
                        .lineSpacing(24)
                    }
                    .padding(.horizontal, 16)
                    .padding(.vertical, 13)
                    .frame(width: 327, height: 50)
                    .background(Color(red: 0.97, green: 0.98, blue: 0.99))
                    .cornerRadius(8)
                    .overlay(RoundedRectangle(cornerRadius: 8).stroke(Color(red: 0.91, green: 0.93, blue: 0.95), lineWidth: 1))
                    .frame(maxWidth: .infinity, maxHeight: 50)

                    HStack(spacing: 180) {
                        Text("Password")
                        .font(.callout)
                        .lineSpacing(24)

                        Text("Show")
                        .font(.callout)
                        .lineSpacing(24)
                    }
                    .padding(.horizontal, 16)
                    .padding(.vertical, 13)
                    .frame(width: 327, height: 50)
                    .background(Color(red: 0.97, green: 0.98, blue: 0.99))
                    .cornerRadius(8)
                    .overlay(RoundedRectangle(cornerRadius: 8).stroke(Color(red: 0.91, green: 0.93, blue: 0.95), lineWidth: 1))
                    .frame(maxWidth: .infinity, maxHeight: 50)
            }
            .frame(width: 327)

            Text("Don’t have a account? Register")
            .fontWeight(.medium)
            .font(.callout)
            .lineSpacing(24)

            Text("Log In")
            .fontWeight(.medium)
            .font(.callout)
            .lineSpacing(24)
            .padding(.horizontal, 32)
            .padding(.vertical, 16)
            .frame(width: 327)
            .background(Color(red: 0, green: 0.50, blue: 1))
            .cornerRadius(8)

            Text("Forgot your password?")
            .fontWeight(.medium)
            .font(.callout)
            .lineSpacing(24)

            ZStack {
                    Rectangle()
                    .fill(Color(red: 0.91, green: 0.93, blue: 0.95))
                    .frame(width: 375, height: 291)
                    .frame(width: 375, height: 291)

                    RoundedRectangle(cornerRadius: 100)
                    .fill(Color(red: 0.11, green: 0.14, blue: 0.18))
                    .frame(width: 134, height: 5)
                    .padding(.leading, 121)
                    .padding(.trailing, 120)
                    .padding(.top, 21)
                    .padding(.bottom, 8)
                    .offset(x: 0, y: 128.50)
                    .frame(width: 375, height: 34)

                    ZStack {
                    Group {
                            Text("Go")
                            .font(.callout)
                            .multilineTextAlignment(.center)
                            .frame(width: 88, alignment: .top)
                            .lineSpacing(21)
                            .padding(.top, 11)
                            .padding(.bottom, 10)
                            .frame(width: 88, height: 42)
                            .background(Color(red: 0.65, green: 0.69, blue: 0.75))
                            .cornerRadius(8)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 137.50, y: 45.50)
                            .frame(width: 88, height: 42)

                            Text("space")
                            .font(.callout)
                            .multilineTextAlignment(.center)
                            .frame(width: 182, alignment: .top)
                            .lineSpacing(21)
                            .padding(.top, 11)
                            .padding(.bottom, 10)
                            .frame(width: 182, height: 42)
                            .background(Color.white)
                            .cornerRadius(8)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -3.50, y: 45.50)
                            .frame(width: 182, height: 42)

                            Text("123")
                            .font(.callout)
                            .multilineTextAlignment(.center)
                            .frame(width: 87, alignment: .top)
                            .lineSpacing(21)
                            .padding(.top, 11)
                            .padding(.bottom, 10)
                            .frame(width: 87, height: 42)
                            .background(Color(red: 0.65, green: 0.69, blue: 0.75))
                            .cornerRadius(8)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -144, y: 45.50)
                            .frame(width: 87, height: 42)

                            ZStack {
                                    Text(" ")
                                    .font(.callout)
                                    .multilineTextAlignment(.center)
                                    .frame(width: 42, alignment: .top)
                                    .lineSpacing(21)
                                    .padding(.top, 11)
                                    .padding(.bottom, 10)
                                    .frame(width: 42, height: 42)
                                    .background(Color(red: 0.65, green: 0.69, blue: 0.75))
                                    .cornerRadius(8)
                                    .shadow(radius: 0, y: 1)
                                    .frame(width: 42, height: 42)
                            }
                            .offset(x: 160.50, y: -8.50)
                            .frame(width: 42, height: 42)

                            ZStack {
                                    Text(" ")
                                    .font(.title)
                                    .padding(.leading, 20)
                                    .padding(.trailing, 22)
                                    .padding(.top, 8)
                                    .padding(.bottom, 7)
                                    .frame(width: 42, height: 42)
                                    .background(Color.white)
                                    .cornerRadius(4.60)
                                    .shadow(radius: 0, y: 1)
                                    .offset(x: -3, y: -116)
                                    .frame(width: 42, height: 42)

                                    RoundedRectangle(cornerRadius: 8)
                                    .fill(Color(red: 0.11, green: 0.14, blue: 0.18))
                                    .offset(x: -2.90, y: -116.57)
                                    .frame(width: 18.88, height: 16.46)
                            }
                            .offset(x: -166.50, y: -8.50)
                            .frame(width: 42, height: 42)

                            Text("M")
                            .font(.title)
                            .padding(.horizontal, 6)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 110.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("N")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 72.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("B")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 34.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("V")
                            .font(.title)
                            .padding(.horizontal, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -2.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("C")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -40.50, y: -8.50)
                            .frame(width: 32, height: 42)
                    }
                    Group {
                            Text("X")
                            .font(.title)
                            .padding(.horizontal, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -77.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("Z")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -115.50, y: -8.50)
                            .frame(width: 32, height: 42)

                            Text("L")
                            .font(.title)
                            .padding(.leading, 10)
                            .padding(.trailing, 9)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 147.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("K")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 109.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("J")
                            .font(.title)
                            .padding(.leading, 10)
                            .padding(.trailing, 9)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 72.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("H")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 34.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("G")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -2.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("F")
                            .font(.title)
                            .padding(.leading, 10)
                            .padding(.trailing, 9)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -40.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("D")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -77.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("S")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -115.50, y: -62.50)
                            .frame(width: 32, height: 42)
                    }
                    Group {
                            Text("A")
                            .font(.title)
                            .padding(.horizontal, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -152.50, y: -62.50)
                            .frame(width: 32, height: 42)

                            Text("P")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 165.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("O")
                            .font(.title)
                            .padding(.horizontal, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 128.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("I")
                            .font(.title)
                            .padding(.leading, 13)
                            .padding(.trailing, 12)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 90.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("U")
                            .font(.title)
                            .padding(.leading, 8)
                            .padding(.trailing, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 53.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("Y")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: 15.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("T")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -21.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("R")
                            .font(.title)
                            .padding(.leading, 9)
                            .padding(.trailing, 8)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -59.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("E")
                            .font(.title)
                            .padding(.horizontal, 9)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -96.50, y: -116.50)
                            .frame(width: 32, height: 42)

                            Text("W")
                            .font(.title)
                            .padding(.horizontal, 5)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -134.50, y: -116.50)
                            .frame(width: 32, height: 42)
                    }
                    Group {
                            Text("Q")
                            .font(.title)
                            .padding(.horizontal, 7)
                            .padding(.top, 8)
                            .padding(.bottom, 7)
                            .frame(width: 32, height: 42)
                            .background(Color.white)
                            .cornerRadius(4.60)
                            .shadow(radius: 0, y: 1)
                            .offset(x: -171.50, y: -116.50)
                            .frame(width: 32, height: 42)
                    }
                    }
                    .offset(x: 0, y: -8)
                    .frame(width: 369, height: 259)
            }
            .frame(width: 375, height: 291)
            .background(Color(red: 0.91, green: 0.93, blue: 0.95))
        }
        .frame(width: 375, height: 812)
        .background(Color.white)
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
